### PR TITLE
Add wrapping array related objects

### PR DESCRIPTION
**Pull request by PeetHornak**

### CODE REVIEW

**Comment by polcak** [comment]
Thank you.

I created an updated branch with modified versions of the proposed commits: 4c7202f83496383182cea5d5d9f5f940239fd383 and 06b27c43388bcc1964b1e9f3c559ceb36daa2be5.

My main question is if all the Proxy objects needs to be wrapped or if it is possible to wrap only those proxies created in wrappingS-ARRAY (wrappingS-ECMA-ARRAY)?

The following modifications might be necessary also in related pull requests. Can you go through all of them and make sure that these issues are fixed, please?
* Indentation fix: I am trying to use tabs for indentation.
* The naming of the wrappings is based on the convention established by https://github.com/pes10k/web-api-manager, i.e. the naming convention established by Peter Snyder, Lara Ansari, Cynthia Taylor, and Chris Kanich, “Browser Feature Usage on the Modern Web,” in Proceedings of the 2016 Internet Measurement Conference, 2016. You can find the relevant standard, for example, in MDN, e.g. for Arrays see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array#Specifications.
  * I renamed wrapping-S-ARRAY.js to wrapping-S-ECMA-ARRAY.js and wrapping-S-PROXY.js to wrapping-S-ECMA-PROXY.js and the original wrapping-S-ECMA.js to wrapping-S-ECMA-DATE.js.
* I linked the level3 ["window.DataView", true] comment with the code inserting additional lines.
```
+               // ARRAY + see the insert_array_wrappings() below
-let arrays = ["Uint8Array", "Int8Array", "Uint8ClampedArray", "Int16Array", "Uint16Array",     "Int32Array", "Uint32Array
", "Float32Array", "Float64Array"];
-for (let a of arrays) {
-       level_3.wrappers.push([`window.${a}`, true]);
-}
+(function insert_array_wrappings() {
+       let arrays = ["Uint8Array", "Int8Array", "Uint8ClampedArray", "Int16Array",
+                       "Uint16Array", "Int32Array", "Uint32Array", "Float32Array", "Float64Array"];
+       for (let a of arrays) {
+               level_3.wrappers.push([`window.${a}`, true]);
+       }
+})();
+
```
* I inserted the correct copyright in file headers.
```
-//  Copyright (C) 2019  Libor Polcak
+//  Copyright (C) 2020 Peter Horňák
```
* For the options, I created a common listener to handle hiding of the sub-options. See f7146a6.
* I marked all borrowed functions specifically, i.e. do not use "Next 4 function were adopted from ..."
* I used Doxygen comments /// instead of // in the array wrapping file.

**Comment by PeetHornak** [comment]
7bcc5149b5a0bbdc7452929b5deb31c375acdd3a - Use modified proxy to typedArrays only
All following commits starting with 7bcc5149b5a0bbdc7452929b5deb31c375acdd3a are changes of code style only following your notes.

I suggest to merge all of these commits together (squashed maybe) as they are related to one subtask.

**Comment by PeetHornak** [comment]
I also added changes following your notes to other pull requests. 

On top of that I had to pull new changes from rewrite to my fork and merge it to these branches, so I could use `connect_options_group` function in `options.js`

**Comment by polcak** [comment]
Well, AFAIK 18f2218 causes a complete mess:
```
* e1aef8d (hornak/ph/jsr-arrays) Add proposed changes
* 6fecc24 Fix user interface to work with common function
* 184b2f4 Replace 4 spaces with 1 tab
* 7bcc514 Use modified Proxy only in typedArrays wrapping
* 728d211 Arrays use common function to getElement
*   18f2218 Merge branch 'ph/jsr-arrays' of https://github.com/PeetHornak/jsrestrictor into ph/jsr-arrays
|\  
| * 5fbe85b Add wrapping of objects representing ArrayBuffer
| * 804b5ac Wrapping of Proxy object
* | 3d72267 Add wrapping of objects representing ArrayBuffer
* | a3f4f16 Wrapping of Proxy object
* |   ccb40b7 (hornak/rewrite) Merge pull request #1 from polcak/rewrite
|\ \  
| |/  
|/|   
| * 68cad9a (origin/rewrite, rewrite) css: Add more space to new/edit level settings
| ...
* | d78e1dd Prepare information planned for the 0.3 release

```

I guess you do not have a simple strategy like cherry-pick x, y, z, squash them, cherry-pick a,b,c, squash them or even better your branch with the correct history?

**Comment by polcak** [comment]
Nevermind, I managed to go further by:

```
git cherry-pick a3f4f16 3d72267 728d211 7bcc514 184b2f4 6fecc24 e1aef8d
```

And the squashed all together.

So I propose to merge c49e9d2cc5232e56d977e1dd63995a5bd77ffc06 and close this pull request. Is it OK?

**Comment by PeetHornak** [comment]
Oh yes, thank you. I squashed it here aswell but I'm not used to it so it was kinda messy.
c49e9d2cc5232e56d977e1dd63995a5bd77ffc06 looks good so I'm closing this.

**Pull request closed without merging**
