### PR TITLE
Add wrapping of battery status API

### PR DESCRIPTION
**Pull request by PeetHornak**
Add wrapping of battery status API by default on every level except level 0.

### CODE REVIEW

**Comment by polcak** [comment]
What is the reasoning behind user not being allowed to influence the wrapping?

See 1b28c14, is it OK?

**Comment by polcak** [comment]
Lines 31-35 of common/wrappingS-BATTERY-CR.js can be removed, see 1b28c14541aa2f21e99d9d7ff85fac79fc1d8b49.

**Comment by PeetHornak** [comment]
Based on https://lukaszolejnik.com/AssessingPrivacyWebStandardsIWPE17.pdf 
see IV. USE AND MISUSE OF THE API IN THE WILD - A.  Statistics on usage in the wild
 that battery status API is mostly used by malicous software and also disabled in most of the browser except Google Chrome, I assumed that protecting users by default could be a good option.

**Comment by PeetHornak** [comment]
```			helping_code: `
				if (navigator.getBattery === undefined) {
					return;
				}
			`,```
I added this code because on Firefox this wrapping was throwing errors. If I remember correctly it was because of calling `navigator.getBattery.toString()` when adding `getBattery` to `original_functions` array.

**Comment by PeetHornak** [comment]
Other than that, it is OK.

**Comment by polcak** [comment]
A agree with adding the API to all levels. However, there might be situations where users might want to define custom level with the API allowed.

I am leaving open for possible preselect checkbox that will allow custom levels to turn Battery API off.

**Comment by PeetHornak** [comment]
I added Battery checkbox to options.js see b7e55b7247dd962f2997ff40d06fbdb15b35bcc8

**Comment by PeetHornak** [comment]
I split options.js into this commit eb416cf94cdb4fac5c7b2e9893887afbb7fb8c3b

**Comment by polcak** [comment]
Modified into b545caa, the wrapping is preselected to give the user a hint that it does not make sense not to wrap the API.

**Pull request closed without merging**
