### PR TITLE
Add locale support and Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by polcak** [comment]
Hello Thank you for your work. At first sight it looks great. We will need some time to go through the patch as it is quite large. I hope that we will be able to merge soon.

**Comment by polcak** [comment]
Hello @TotalCaesar659.

I am sorry that this took much longer than expected. First let me thank you for the work on the proposed patch. We intend to release an internationalizable version of the extension soon. In fact we have a branch ready: https://pagure.io/JShelter/webextension/tree/i18n. The main work happen in https://pagure.io/JShelter/webextension/c/bff8ce9c69ca28c1952898125983429c1f7f8a32?branch=i18n and you might notice that your work was a basis for that patch. Thanks again.

However, you can also notice that I needed to make some modifications, like merged strings and so on. We have also tweaked some English original. Can you go through https://github.com/polcak/jsrestrictor/blob/i18n_ru/common/_locales/ru/messages.json (and https://github.com/polcak/jsrestrictor/blob/i18n_ru/common/_locales/en/messages.json) andcheck that I did not break anything and provide the missing strings.

Thank you.

**Comment by TotalCaesar659** [comment]
Hi @polcak, nice to hear you again! It's better late than never, thank you for all your work. I updated Russian translation and made some fixes for English [here](https://github.com/polcak/jsrestrictor/pull/203).
P.S. I can't build it now, it gives me error (last time I tested it more than year ago). So if you upload artifacts for both browsers with them here in comments, I'll be grateful and test for the need for a further fix.

**Comment by polcak** [comment]
I am closing this one as we moved to #203.

**Pull request closed without merging**
